version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: university_postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "SuperStrongPassword123!"
      POSTGRES_DB: "WirtualnyDziekanat"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d WirtualnyDziekanat"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: unless-stopped